### ISSUE TITLE
Properly attach to all relevant tooltips

### ISSUE THREAD

**Issue by JoVoCop** [JoVoCop/SOD_BISListTooltip#8]
See https://legacy.curseforge.com/wow/addons/sod_bislisttooltip#c9 for initial issue. I've fixed this by changing `ShoppingTooltip` to `ShoppingTooltip1` and `ShoppingTooltip2`.

I should review all available tooltips and attach to the relevant ones. For example, should I attach to `ItemRefShoppingTooltip1` and `ItemRefShoppingTooltip2`?

**Comment by Arby69** [comment]
ItemRefShoppingTooltip1 and ItemRefShoppingTooltip2 seem to be the tooltips that display when you compare items with the ones you already have equipped (they are two because of rings and trinkets).
I tried already to include those two into your tooltip hook and it worked. Much better as you can determine if your equipped item is already a higher rank from the BiS list.
